version: "3.8"

services:
  db:
    image: postgres
    container_name: pg_container
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data:
